# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        filename: 'verademo.war' 
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Veracode Upload And Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-uploadandscan-action@c3c0b78bddb42d5f6b10d70562f692215a410d7b
      # comment for push
      uses: veracode/veracode-uploadandscan-action@v1.0
      with:
            appname: VeraDemo-GitHub
      # createprofile
            createprofile: true
      # filepath
            filepath: '**/**.war'
      # version
            version: ${{ GITHUB.RUN_ID }}
      # vid
            vid: ${{ secrets.VERACODE_API_ID }}
      # vkey
            vkey: ${{ secrets.VERACODE_API_KEY }}
          
    - name: Download the Agent Based SCA Scanner
        
      env: # Set the secret as an input
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh      
